### ISSUE TITLE
TypeError: Cannot read property 'Id' of undefined

### ISSUE THREAD

**Issue by sic2** [ajermakovics/jvm-mon#21]
I got the following error while running jvm-mon. Not sure if there are logs I can inspect or not.

```bash
$ jvm-mon
TypeError: Cannot read property 'Id' of undefined
    at renderVmCharts (/usr/local/Cellar/jvm-mon/0.3/libexec/jvm-mon.js:174:25)
    at addData (/usr/local/Cellar/jvm-mon/0.3/libexec/jvm-mon.js:150:9)
    at Timeout._repeat (/usr/local/Cellar/jvm-mon/0.3/libexec/jvm-mon.js:204:5)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)
```

**Comment by ajermakovics** [comment]
Hmm, appears to be this line: https://github.com/ajermakovics/jvm-mon/blob/4d9a4fe21bf5283f2341a58b1b983b4eea8f597d/src/dist/jvm-mon.js#L173-L174
where 'vm' ends up undefined.

Does this happen on startup or after some action?

**Comment by sic2** [comment]
This does not happen with all my java programs. Anyway, it happens as soon as I try to inspect a java process.

**Comment by makaraset** [comment]
I'm facing with this error too in centos.

**Comment by ajermakovics** [comment]
Unfortunately, I'm not able to reproduce this issue.
Does it prevent you from monitoring all processes or just one?
