### ISSUE TITLE
stack guard warning and IOException when starting

### ISSUE THREAD

**Issue by LemADEC** [ajermakovics/jvm-mon#25]
I'm unable to start the application due to some IOException. There's also warnings related to stack guard:
```
bin/jvm-mon
OpenJDK 64-Bit Server VM warning: You have loaded library /home/minecraft/jvm-mon-0.3/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
java.io.IOException: well-known file is not secure
        at sun.tools.attach.LinuxVirtualMachine.checkPermissions(Native Method)
        at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:117)
        at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        at com.jvmtop.openjdk.tools.LocalVirtualMachine.loadManagementAgent(LocalVirtualMachine.java:341)
        at com.jvmtop.openjdk.tools.LocalVirtualMachine.startManagementAgent(LocalVirtualMachine.java:141)
        at com.jvmtop.openjdk.tools.ProxyClient.tryConnect(ProxyClient.java:372)
        at com.jvmtop.openjdk.tools.ProxyClient.connect(ProxyClient.java:354)
        at com.jvmtop.monitor.VMInfo.attachToVM(VMInfo.java:219)
        at com.jvmtop.monitor.VMInfo.processNewVM(VMInfo.java:186)
        at com.jvmtop.view.VMOverviewView.scanForNewVMs(VMOverviewView.java:176)
        at JvmMon.update(JvmMon.java:50)
        at JvmMon.<init>(JvmMon.java:45)
        at JvmMon.main(JvmMon.java:27)
```

This is on CentOS Linux release 7.4.1708 (Core)
with
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**Comment by perrefe** [comment]
+1
Same exception here.

**Comment by mferretti** [comment]
+1
Same here

**Comment by ajermakovics** [comment]
This might happen if you run as a different user: https://stackoverflow.com/q/9100149/1180621

**Comment by ajermakovics** [comment]
Just made a new release:
https://github.com/ajermakovics/jvm-mon/releases
It's a complete re-write of jvm-mon so should not have this issue
